### PR TITLE
Introduce pat_adjustments table

### PR DESCRIPTION
**Pull request by tbg**
wip: implement pattern-binding-modes RFC

See the [RFC] and [tracking issue].

This is a work in progress. The basic examples from the RFC are in place and work,
but there are still some obvious deficiencies (some of which documented through
currently problematic tests).

Commentary is sparse. This will be improved before merging.

[tracking issue]: https://github.com/rust-lang/rust/issues/42640
[RFC]: https://github.com/rust-lang/rfcs/blob/491e0af/text/2005-match-ergonomics.md

---
This change is [Reviewable](https://reviewable.io/reviews/tschottdorf/rust/1)

### CODE REVIEW

**Comment by tbg** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/librustc/ty/sty.rs, line 160 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqErkW8Wh2i8ph1Uj:-KsPqErkW8Wh2i8ph1Uk:blegat7) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc/ty/sty.rs#L160)):*
@nikomatsakis wrote:

> I don't really understand what you are concerned about in this line of code.
> here, Thing means "some generic type"?
shouldn't be a problem, I don't think, because when we type-check, we don't know what T is, so we would decide (in this case) not to insert a deref etc
i.e., in the desugared version, after type-check, match t { _ => (), } would be unchanged

---

*[src/librustc_const_eval/pattern.rs, line 306 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqSr77oP3mBvw76-d:-KsPqSr77oP3mBvw76-e:b-fhwvdc) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_const_eval/pattern.rs#L306)):*
@nikomatsakis wrote:

> the comment on this line sounds about right. And this loop [below] also seems about right; to adjust ty, you can simply match on it --
it must be a TyRef or else something went wrong somewhere
so you could do like `ty = match ty.sty { TyRef(_, mt) => mt.ty, _ => bug!() };`

---

*[src/librustc_typeck/check/_match.rs, line 167 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqmk8i2p95ZYSrHAH:-KsPqmk8i2p95ZYSrHAI:bqdbunj) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L167)):*
> ```Rust
>             }
>             PatKind::Path(ref qpath) => {
>                 // FIXME(tschottdorf): careful about const ref types.
> ```

@nikomatsakis here I'm just pointing out that it is where we'll end up for `const CONST_REF_TYPE: &[u8] = b"foo"; match something { CONST_REF_TYPE => ... }`. I.e. if the qpath comes from such a const then we must treat it as a ref pattern and can't use default binding modes. (Right?).

---

*[src/librustc_typeck/check/_match.rs, line 631 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPr9wtTC2iE1qf9FfE:-KsPr9wtTC2iE1qf9FfF:bsmm22k) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L631)):*
@nikomatsakis wrote:

> this seems right, but I suspect that the code will not go in check_pat_path() but rather somewhere more general-- that is, I think we want to insert an autoderef whenever:
the type is & (TyRef)
the pat is one of those enumerated kinds that cannot be a tuple (e.g., (), non-binding path, ...)
I forget where we resolve whether a path is a binding or not
I think before type-check though

---

*[src/librustc_typeck/check/_match.rs, line 684 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPrM5Dh-IH3E_zK7bB:-KsPrM5Dh-IH3E_zK7bC:b-7g067q) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L684)):*
@nikomatsakis wrote:

> similarly, on this line, I don't really expect there to be many changes needed -- that is, I don't think that check_pat_tuple_struct() itself will have to change much. I expect the adaptation to happen at the top of check_pat_arg()

---

*[src/librustc_typeck/check/_match.rs, line 695 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPrSyucnnyN4MJzMQc:-KsPrSyucnnyN4MJzMQd:b-sn11ik) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L695)):*
@nikomatsakis wrote:

> my expectation is that check_pat_arg() will grow a 4th argument

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tschottdorf/rust/1)*

**Comment by tbg** [comment]
Made some progress writing code that I think is "roughly correct" to populate `pat_adjustments`. Let me know what you think!

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/librustc_const_eval/pattern.rs, line 318 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPt352gEknPi4FovtK:-KsPt352gEknPi4FovtL:b-bydc6x) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_const_eval/pattern.rs#L318)):*
> ```Rust
>                 // Probably involves ty::TypeVariants::TyRef.
>                 //
>                 // NB: trying to stuff new things into the HIR is probably a bad idea.
> ```

What do you think about this, @nikomatsakis? In particular, I don't know how to generate a new `id` and `hir_id`.

---

*[src/librustc_typeck/check/_match.rs, line 631 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPr9wtTC2iE1qf9FfE:-KsPtQtJAa69ErTjmDhJ:b-mpl31b) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L631)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis wrote:

> this seems right, but I suspect that the code will not go in check_pat_path() but rather somewhere more general-- that is, I think we want to insert an autoderef whenever:
the type is & (TyRef)
the pat is one of those enumerated kinds that cannot be a tuple (e.g., (), non-binding path, ...)
I forget where we resolve whether a path is a binding or not
I think before type-check though
</blockquote></details>

Ok. How do I find out? I'm not sure what to look for.

---

*[src/librustc_typeck/check/_match.rs, line 695 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPrSyucnnyN4MJzMQc:-KsPuZfyaMKrUQedAZnV:b-u9lvnz) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L695)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis wrote:

> my expectation is that check_pat_arg() will grow a 4th argument
</blockquote></details>

Did the plumbing. Please check that I terminated it correctly - the binding mode begins in `check_match` and `check_local_decl` as `ty::BindingMode::BindByValue(hir::Mutability::MutImmutable)`. I think this roughly corresponds to `let <pat> = ...` and `match x { <pats> }`. Am I somehow missing other things that want to match patterns?

---

*[src/librustc/ty/sty.rs, line 160 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqErkW8Wh2i8ph1Uj:-KsPsuK4w2dX1D37qkhj:b-g2z0ca) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc/ty/sty.rs#L160)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis wrote:

> I don't really understand what you are concerned about in this line of code.
> here, Thing means "some generic type"?
shouldn't be a problem, I don't think, because when we type-check, we don't know what T is, so we would decide (in this case) not to insert a deref etc
i.e., in the desugared version, after type-check, match t { _ => (), } would be unchanged
</blockquote></details>

Ack, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tschottdorf/rust/1#-:-KsQWhLxCYqjKerJfCRQ:b-3zluqf)*

**Comment by nikomatsakis** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/librustc_const_eval/pattern.rs, line 318 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPt352gEknPi4FovtK:-KseVvEGYL-vadOL4g9x:bl4jh2x) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_const_eval/pattern.rs#L318)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What do you think about this, @nikomatsakis? In particular, I don't know how to generate a new `id` and `hir_id`.
</blockquote></details>

I think the thing to do here is not construct new HIR, but rather to just change the pattern that gets returned. I think what I would expect is that we do not generate a new `pat`, but rather we dereference `ty` once for each autoderef, and then, at the end, we take the `Pattern<'tcx>` that would have been returned, and wrap it in various `PatternKind::Deref` wrappers. Does that make sense?

---

*[src/librustc_typeck/check/_match.rs, line 167 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqmk8i2p95ZYSrHAH:-KseWrfOoTeQ4reDiiUw:bm4t11y) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L167)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis here I'm just pointing out that it is where we'll end up for `const CONST_REF_TYPE: &[u8] = b"foo"; match something { CONST_REF_TYPE => ... }`. I.e. if the qpath comes from such a const then we must treat it as a ref pattern and can't use default binding modes. (Right?).
</blockquote></details>

yes -- I think that's right

---

*[src/librustc_typeck/check/_match.rs, line 631 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPr9wtTC2iE1qf9FfE:-KseXti_k36-1xOJfqSR:b-1h0toa) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L631)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ok. How do I find out? I'm not sure what to look for.
</blockquote></details>

based on the function `check_pat_path` in `_match.rs`, it looks like `PatKind::Path` refers to a const variant (e.g., `None`) or a constant

---

*[src/librustc_typeck/check/_match.rs, line 695 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPrSyucnnyN4MJzMQc:-KseYW6K6x7Ett_mvnsw:b-2wh42s) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L695)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Did the plumbing. Please check that I terminated it correctly - the binding mode begins in `check_match` and `check_local_decl` as `ty::BindingMode::BindByValue(hir::Mutability::MutImmutable)`. I think this roughly corresponds to `let <pat> = ...` and `match x { <pats> }`. Am I somehow missing other things that want to match patterns?
</blockquote></details>

Looks...pretty good to me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tschottdorf/rust/1#-:-KseYYWS6BYDMlQ1-SfL:bb6ywmx)*

**Comment by tbg** [comment]
Ok, I think this is now functional enough to open a PR on the main repo. What do you think, @nikomatsakis?

---

Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/librustc_const_eval/pattern.rs, line 318 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPt352gEknPi4FovtK:-Ktyho8Jlz_3MFJSPjUW:b-896fix) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_const_eval/pattern.rs#L318)):*
<details><summary><i>Previously, nikomatsakis (Niko Matsakis) wrote…</i></summary><blockquote>

I think the thing to do here is not construct new HIR, but rather to just change the pattern that gets returned. I think what I would expect is that we do not generate a new `pat`, but rather we dereference `ty` once for each autoderef, and then, at the end, we take the `Pattern<'tcx>` that would have been returned, and wrap it in various `PatternKind::Deref` wrappers. Does that make sense?
</blockquote></details>

Done.

---

*[src/librustc_typeck/check/_match.rs, line 167 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqmk8i2p95ZYSrHAH:-KtyhqLsKKT1eyICXREJ:b-rqmbd5) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L167)):*
<details><summary><i>Previously, nikomatsakis (Niko Matsakis) wrote…</i></summary><blockquote>

yes -- I think that's right
</blockquote></details>

Haven't done this yet, but the comment is still in the code, so I'll get around to it.

---

*[src/librustc_typeck/check/_match.rs, line 631 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPr9wtTC2iE1qf9FfE:-KtyhxRqKYFl5H9jP8Zh:b-896fix) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L631)):*
<details><summary><i>Previously, nikomatsakis (Niko Matsakis) wrote…</i></summary><blockquote>

based on the function `check_pat_path` in `_match.rs`, it looks like `PatKind::Path` refers to a const variant (e.g., `None`) or a constant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tschottdorf/rust/1#-:-Ktyhhxmz-1qgcRFHVa0:b-y3hjsp)*

**Comment by nikomatsakis** [comment]
Reviewed 206 of 206 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/librustc_const_eval/pattern.rs, line 306 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPqSr77oP3mBvw76-d:-Ku3rAutkvIdZ9rU6iBP:b32w0x) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_const_eval/pattern.rs#L306)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis wrote:

> the comment on this line sounds about right. And this loop [below] also seems about right; to adjust ty, you can simply match on it --
it must be a TyRef or else something went wrong somewhere
so you could do like `ty = match ty.sty { TyRef(_, mt) => mt.ty, _ => bug!() };`

</blockquote></details>

OK

---

*[src/librustc_typeck/check/_match.rs, line 684 at r1](https://reviewable.io:443/reviews/tschottdorf/rust/1#-KsPrM5Dh-IH3E_zK7bB:-Ku3sLafriDyBiMHpYi_:bb6ywmx) ([raw file](https://github.com/tschottdorf/rust/blob/a12b995ced4693a4818c40f10562a0b44ef4b836/src/librustc_typeck/check/_match.rs#L684)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@nikomatsakis wrote:

> similarly, on this line, I don't really expect there to be many changes needed -- that is, I don't think that check_pat_tuple_struct() itself will have to change much. I expect the adaptation to happen at the top of check_pat_arg()
</blockquote></details>

LGTM

---

*[src/librustc_typeck/check/_match.rs, line 51 at r2](https://reviewable.io:443/reviews/tschottdorf/rust/1#-Ku3rQPKQ-p0RzVEzmr6:-Ku3rQPKQ-p0RzVEzmr7:b62gxha) ([raw file](https://github.com/tschottdorf/rust/blob/bb34d5077a1f390140ea2ba85e4f881887f6d37d/src/librustc_typeck/check/_match.rs#L51)):*
> ```Rust
>             PatKind::Tuple(..) |
>             PatKind::Box(_) |
>             // PatKind::Lit(_) | // FIXME(tschottdorf): causes lots of errors
> ```

Hmm I guess I have to check out what produces a `PatKind::Lit`. I am not crazy about the idea of poking at the type of the literal. If I had to *guess*, I would guess that the problems with literals come about because of things like matching `"foo"` against an `&str`, maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tschottdorf/rust/1)*

**Comment by tbg** [comment]
Closing this. Will open a PR against the main repo next.

**Pull request closed without merging**
